export default interface ItemModel {
    id?: number
    itemId: number;
    itemName: string;
    itemQty: number;
    itemCode: string;
    createdDateTime: string;
    itemAmount: number;
    itemBarcode: string;
    itemUnder: number;
    itemNameLao: string;
    itemNameEng: string;
    itemSKU: string;
    itemUnit: string;
    itemSalePrice1: number;
    itemSalePrice2: number;
    itemSalePrice3: number;
    itemSalePrice4: number;
    itemSalePrice5: number;
    itemSaleDiscount: number;
    itemSaleCurrency: number;
    itemBuyPrice: number;
    itemBuyCurrency: number;
    nbUnit: number;
    serialRunning: number;
    itemCategoryId: number;
    supplierId: number;
    itemTypeId: number;
    purchaseAccount: number;
    saleAccount: number;
    stockAccount: number;
    itemStatus: number;
    userEntry: number;
    dateEntry: string;
}

export const listItemValue:ItemModel = {
    createdDateTime: "",
    itemAmount: 0,
    itemName: "",
    itemQty: 0,
    dateEntry: "",
    itemBarcode: "",
    itemBuyCurrency: 0,
    itemBuyPrice: 0,
    itemCategoryId: 0,
    itemCode: "",
    itemId: 0,
    itemNameEng: "",
    itemNameLao: "",
    itemSKU: "",
    itemSaleCurrency: 0,
    itemSaleDiscount: 0,
    itemSalePrice1: 0,
    itemSalePrice2: 0,
    itemSalePrice3: 0,
    itemSalePrice4: 0,
    itemSalePrice5: 0,
    itemStatus: 0,
    itemTypeId: 0,
    itemUnder: 0,
    itemUnit: "",
    nbUnit: 0,
    purchaseAccount: 0,
    saleAccount: 0,
    serialRunning: 0,
    stockAccount: 0,
    supplierId: 0,
    userEntry: 0
}