export default interface OrderPayModel {
    Stepid: number;
    StepName: string;
    States: string;
    Status: number;
    isCurrent: boolean;
    Name: string;
    discountAmount: number,
    Value1: number;
    Value2: number;
    id: number;
    Id?: number;
    voucherNo: string;
    orderNo: string;
    branchId: number;
    docType: number;
    paidDate: string;
    paidAmount: number;
    paidcurrencyId: number;
    paidAmountOriginal: number;
    rateId: number;
    bankId: number;
    chequeNo: string;
    chequeDate: string;
    currencyId: number;
    currencyName: string;
    taxValue: number;
    taxAmount: number;
    paymetType: number;
    paymetTypeName: string;
    totalPaid: number;
    remark: string;
    createdById: number;
    updatedById: number;
}

export const OrderPayModelValue: OrderPayModel = {
    bankId: 0,
    branchId: 0,
    chequeDate: "",
    chequeNo: "",
    createdById: 0,
    currencyId: 1,
    currencyName: "",
    docType: 3,
    orderNo: "",
    paidAmount: 0,
    paidAmountOriginal: 0,
    paidDate: "",
    paidcurrencyId: 0,
    paymetType: 0,
    paymetTypeName: "",
    rateId: 0,
    remark: "",
    taxAmount: 0,
    taxValue: 0,
    totalPaid: 0,
    updatedById: 0,
    voucherNo: "",
    Name: "",
    id: 0,
    Value1: 0,
    Value2: 0,
    States: "",
    Status: 0,
    discountAmount: 0,
    Stepid: 0,
    StepName: "",
    isCurrent: false
}